services:
  springapp:
    build: .
    ports:
      - "9090:9090"
    env_file:
      - .env
    networks:
      - kayros-shared-net

  networks:
    kayros-shared-net:
      external: true
      name: kayros-network
