version: '3'
services:
  springapp:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PRINCIPAL_DATABASE=${PRINCIPAL_DATABASE}
      - PRINCIPAL_DATABASE_USERNAME=${PRINCIPAL_DATABASE_USERNAME}
      - PRINCIPAL_DATABASE_PASSWORD=${PRINCIPAL_DATABASE_PASSWORD}
      - KEY_PRIVATE=${KEY_PRIVATE}
      - USER_GENERATOR=${USER_GENERATOR}
      - FRONTEND_ROUTE1=${FRONTEND_ROUTE1}
      - FRONTEND_ROUTE2=${FRONTEND_ROUTE2}