spring.application.name=Kairo

# Configuration
server.port=${PORT}

# Kairo Database Configuration
spring.datasource.url=${PRINCIPAL_DATABASE}
spring.datasource.username=${PRINCIPAL_DATABASE_USERNAME}
spring.datasource.password=${PRINCIPAL_DATABASE_PASSWORD}
spring.jpa.open-in-view=false

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create


security.jwt.key.private=${JWT_KEY}
security.jwt.user.generator=${JWT_GENERATOR}

security.users.defaultpass=${DEFAULT_PASS}
frontend.route1=${FRONTEND_URL1}
frontend.route2=${FRONTEND_URL2}

application.title=Kairo
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false